os: linux
language: node_js
node_js: "7.10.1"

before_install:
  - npm install gitbook-cli svgexport -g
  - sudo apt-get -y install calibre ghostscript

script:
  - cd ebook/
  - rm *.epub *.mobi *.pdf || true # Clean up from previous runs
  - sed -i -e 's|2012 - [2][0-9][0-9][0-9]|2012 - '$(date '+%Y')'|g' cover_template.svg # Insert current year into book cover
  - grep -r Copyright cover_template.svg
  - ./create_books.sh en-US fr-FR zh-CN zh-TW

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - OUTPUTS=$(find . -type f -name '*.epub' -or -name '*.mobi' -or -name '*.pdf')
  - bash upload.sh $OUTPUTS
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
