os: linux
language: node_js
node_js: "7.10.1"

before_install:
  - npm install gitbook-cli svgexport -g
  - sudo apt-get -y install calibre ghostscript

script:
  - cd ebook/
  - rm *.epub *.mobi *.pdf || true # Clean up from previous runs
  - ./create_books.sh en-US fr-FR zh-CN

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ebook/*.epub ebook/*.mobi ebook/*.pdf
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
